user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 2048;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;

    log_format vympel_json escape=json
        '{"time":"$time_iso8601","request_id":"$request_id",'
        '"remote_addr":"$remote_addr","host":"$host","method":"$request_method",'
        '"uri":"$uri","status":$status,"bytes":$body_bytes_sent,'
        '"request_time":$request_time,"upstream_time":"$upstream_response_time"}';
    access_log /dev/stdout vympel_json;
    error_log /dev/stderr warn;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    client_header_timeout 15s;
    client_body_timeout 60s;
    reset_timedout_connection on;

    include /etc/nginx/conf.d/*.conf;
}
